SELECT t.*,
       CONDITION_CODE_MANAGER_API.Get_Condition_Code(PART_NO,
                                                     SERIAL_NO,
                                                     LOT_BATCH_NO) condition_code,
       INVENTORY_PART_API.Get_Description(CONTRACT, PART_NO) part_description,
       HANDLING_UNIT_TYPE_API.Get_Description(Handling_Unit_API.Get_Handling_Unit_Type_Id(HANDLING_UNIT_ID)) type_description,
       Condition_Code_API.Get_Description(CONDITION_CODE_MANAGER_API.Get_Condition_Code(PART_NO,
                                                                                        SERIAL_NO,
                                                                                        LOT_BATCH_NO)) condition_code_description,
       Inventory_Part_In_Stock_API.Get_Availability_Control_Id(CONTRACT,
                                                               PART_NO,
                                                               '*',
                                                               LOCATION_NO,
                                                               LOT_BATCH_NO,
                                                               SERIAL_NO,
                                                               ENG_CHG_LEVEL,
                                                               WAIV_DEV_REJ_NO,
                                                               ACTIVITY_SEQ,
                                                               HANDLING_UNIT_ID) availability_control_i_d,
       Part_Availability_Control_API.Get_Description(Inventory_Part_In_Stock_API.Get_Availability_Control_Id(CONTRACT,
                                                                                                             PART_NO,
                                                                                                             '*',
                                                                                                             LOCATION_NO,
                                                                                                             LOT_BATCH_NO,
                                                                                                             SERIAL_NO,
                                                                                                             ENG_CHG_LEVEL,
                                                                                                             WAIV_DEV_REJ_NO,
                                                                                                             ACTIVITY_SEQ,
                                                                                                             HANDLING_UNIT_ID)) availability_control_description,
       Project_API.Get_Program_Id(PROJECT_ID) program_id,
       PROJECT_PROGRAM_GLOBAL_API.Get_Description(Project_API.Get_Program_Id(PROJECT_ID)) program_description,
       PROJECT_API.Get_Name(PROJECT_ID) project_name,
       DECODE(ACTIVITY_SEQ,
              0,
              NULL,
              Activity_API.Get_Sub_Project_Id(ACTIVITY_SEQ)) sub_project_id,
       DECODE(ACTIVITY_SEQ,
              0,
              NULL,
              Activity_API.Get_Sub_Project_Description(ACTIVITY_SEQ)) sub_project_description,
       DECODE(ACTIVITY_SEQ,
              0,
              NULL,
              Activity_API.Get_Activity_No(ACTIVITY_SEQ)) activity_no,
       DECODE(ACTIVITY_SEQ,
              0,
              NULL,
              Activity_API.Get_Description(ACTIVITY_SEQ)) activity_description,
       Handling_Unit_API.Get_Top_Parent_Handl_Unit_Id(HANDLING_UNIT_ID) top_parent_handling_unit_i_d,
       Handling_Unit_API.Get_Top_Parent_Hu_Type_Id(HANDLING_UNIT_ID) top_parent_handling_unit_type_i_d,
       Handling_Unit_Type_API.Get_Description(Handling_Unit_API.Get_Top_Parent_Hu_Type_Id(HANDLING_UNIT_ID)) top_parent_handling_unit_type_desc,
       Handling_Unit_API.Get_Top_Parent_Sscc(HANDLING_UNIT_ID) top_parent_s_s_c_c,
       Handling_Unit_API.Get_Top_Parent_Alt_Hu_Label_Id(HANDLING_UNIT_ID) top_parent_alt_handling_unit_label_i_d,
       Inventory_Part_API.Get_Unit_Meas(CONTRACT, PART_NO) inventory_uo_m,
       Inventory_Part_API.Get_Enabled_Catch_Unit_Meas(CONTRACT, PART_NO) catch_uo_m
  FROM COUNTING_RESULT t
 WHERE to_date(substr(OBJVERSION, 0, 8), 'YYYYMMDD') between
       to_date('20181101', 'YYYYMMDD') AND to_date('20240331', 'YYYYMMDD');
