select t.*,
       t.line_item_no LineItemNumber,
       DECODE(Sales_Part_API.Get_Configurable_Db(CONTRACT, CATALOG_NO),'CONFIGURED','TRUE', 'FALSE') Configurable,
       Customer_Order_Line_API.Get_Interim_Order_No(order_no, line_no, rel_no, line_item_no, ctp_planned_db) InterimOrder,
       Inventory_Part_API.Get_Site_Converted_Qty(supply_site, part_no, Co_Supply_Site_Reservation_API.Get_Qty_Reserved(order_no, line_no, rel_no, line_item_no), contract, 'ADD') SupplySiteReservedQty,
       Input_Unit_Meas_Group_API.Is_Usage_Allowed(Inventory_Part_API.Get_Input_Unit_Meas_Group_Id(contract, Sales_Part_API.Get_Part_No(contract, catalog_no)), 'ORDER') InputUomGroup,
       Sales_Price_List_API.Get_Description(price_list_no) PriceListDescription,
       Customer_Order_Line_API.Get_Owner_For_Part_Ownership(order_no, line_no, rel_no, line_item_no, part_ownership_db) Owner,
       Reserve_Customer_Order_API.Get_Available_Qty(NVL(supply_site, contract), NVL(NVL(supply_site_part_no, part_no), catalog_no), configuration_id, order_no, line_no, rel_no, line_item_no, supply_code_db, part_ownership_db, owning_customer_no, project_id, condition_code, null, 'TRUE') AvailableQty,
       DECODE(catalog_type_db, 'INV', qty_picked, null) PickedQty,
       DECODE(catalog_type_db, 'INV', qty_shipped, null) DeliveredQty,
       part_price + NVL(calc_char_price, 0) TotalCalcSalesPriceCurr,
       Order_Currency_Rate_Util_API.Get_Fin_Curr_Rate(currency_rate, company, currency_code) CurrencyRate,
       Customer_Order_Line_API.Get_Base_Sale_Price_Total(order_no, line_no, rel_no, line_item_no) NetAmtBase,
       Customer_Order_Line_API.Get_Base_Price_Incl_Tax_Total(order_no, line_no, rel_no, line_item_no) GrossAmtBase,
       Customer_Order_Line_API.Get_Sale_Price_Total(order_no, line_no, rel_no, line_item_no) NetAmountCurr,
       Customer_Order_Line_API.Get_Sale_Price_Incl_Tax_Total(order_no, line_no, rel_no, line_item_no) GrossAmtCurr,
       Customer_Order_Line_API.Get_Total_Cost(order_no, line_no, rel_no, line_item_no) TotalCostBase,
       Rental_Object_API.Get_Planned_Rental_Start_Date(rental_no) PlannedRentalStartDate,
       Rental_Object_API.Get_Planned_Rental_Start_Time(rental_no) PlannedRentalStartTime,
       Rental_Object_API.Get_Planned_Rental_Duration(rental_no) PlannedRentalDuration,
       Rental_Object_API.Get_Rental_Duration_Unit_Me_Db(rental_no) RentalDurationUom,
       Rental_Object_API.Get_Planned_Rental_End_Date(rental_no) PlannedRentalEndDate,
       Rental_Object_API.Get_Planned_Rental_End_Time(rental_no) PlannedRentalEndTime,
       Rental_Object_Manager_API.Calculate_Chargeable_Days(Rental_Object_API.Get_Planned_Rental_Start_Date(rental_no), Rental_Object_API.Get_Planned_Rental_End_Date(rental_no), Rental_Object_API.Get_Chargeable_Id(rental_no), Rental_Object_API.Get_Exception_Id(rental_no), Rental_Period_Rounding_API.Encode(Rental_Object_API.Get_Period_Rounding(rental_no))) ChargeableDays,
       Rental_Object_API.Get_Planned_Rental_Return_Date(rental_no) PlannedRentalReturnDate,
       Rental_Object_API.Get_Chargeable_Id(rental_no) ChargeableDaysID,
       Rental_Object_API.Get_Exception_Id(rental_no) DateExceptionID,
       Rental_Object_API.Get_Period_Rounding(rental_no) PeriodRounding,
       Rental_Object_API.Get_Trans_Schedule_Id(rental_no) ScheduleID,
       Rental_Trans_Schedule_API.Get_Description(Rental_Object_API.Get_Trans_Schedule_Id(rental_no)) ScheduleDescription,
       Rental_Object_API.Get_Start_Rental_Option_Db(rental_no) StartRentalOption,
       Statutory_Fee_API.Get_Description(company, tax_code) TaxCodeDescription,
       Tax_Class_API.Get_Description(company, tax_class_id) TaxClassDescription,
       Source_Tax_Item_API.Multiple_Tax_Items_Exist(company,'CUSTOMER_ORDER_LINE',order_no,line_no,rel_no,line_item_no, '*') MultipleTaxLines,
       Customer_Order_Line_API.Get_Total_Tax_Amount_Base(order_no, line_no, rel_no, line_item_no) TaxAmountBase,
       Customer_Order_Line_API.Get_Total_Tax_Amount_Curr(order_no, line_no, rel_no, line_item_no) TaxAmountCurr,
       DECODE(DISC_PRICE_ROUND,'TRUE',DECODE(USE_PRICE_INCL_TAX_DB, 'FALSE',ORIGINAL_DISCOUNT, DISCOUNT),DISCOUNT) Discount,
       DECODE(DISC_PRICE_ROUND,'TRUE',DECODE(USE_PRICE_INCL_TAX_DB, 'FALSE',ORIGINAL_ADD_DISCOUNT, ADDITIONAL_DISCOUNT),ADDITIONAL_DISCOUNT) AdditionalDiscount,
       Customer_Order_Line_API.Get_Total_Discount_Percentage(order_no,line_no,rel_no,line_item_no) TotalOrderLineDiscount,
       Customer_Order_Line_API.Get_Comp_Bearing_Tax_Amount(order_no, line_no, rel_no, line_item_no) CompanyBearingTaxAmountBase,
       Delivery_Route_API.Get_Description(route_id) RouteDescription,
       Rental_Object_API.Get_Primary_Rental_No(order_no, line_no, rel_no, line_item_no, 'CUST ORDER') PrimaryRentalNo,
       Customer_Order_Milestone_API.Milestone_Exist(order_no,line_no,rel_no,line_item_no) MilestoneExists,
       DECODE(Document_Text_API.Note_Id_Exist(NOTE_ID),1,'TRUE','FALSE') DocumentText,
       DECODE(cust_warranty_id,null,'FALSE','TRUE') CustomerWarranty,
       Cust_Ord_Customer_API.Get_Name(end_customer_id) EndCustomerName,
       Mpccom_Ship_Via_API.Get_Description(ship_via_code) ShipViaDescription,
       Order_Delivery_Term_API.Get_Description(delivery_terms) DeliveryTermsDescription,
       Customer_Order_Delivery_API.Get_Latest_Date_Confirmed(order_no,line_no,rel_no,line_item_no) ConfirmedDate,
       Outstanding_Sales_API.Get_Total_Qty_Confirmed(order_no, line_no, rel_no, line_item_no) ConfirmedQty,
       Outstanding_Sales_API.Get_Total_Confirm_Amount(order_no, line_no, rel_no, line_item_no) DeliveryConfirmedNetAmtBase,
       Project_Program_Global_API.Get_Description(Project_API.Get_Program_Id(project_id)) ProgramDescription,
       Activity_API.Get_Sub_Project_Description(activity_seq) SubProjectDescription,
       Order_Cancel_Reason_API.Get_Reason_Description(cancel_reason) CancellationReasonDescription,
       Sales_Part_API.Get_Gtin_No(contract, catalog_no, input_unit_meas) Gtin,
       Part_Catalog_API.Get_Freight_Factor(NVL(part_no,catalog_no)) FreightFactor,
       Customer_Order_Line_API.Check_Pegged_Component_Exist(order_no, line_no, rel_no, line_item_no) PeggedCompExist,
       Currency_Code_API.Get_Currency_Rounding(company,currency_code) CurrencyRounding,
       Pick_Customer_Order_API.Reserved_As_Picked_Allowed__(order_no,line_no,rel_no,line_item_no) PickReservedQty,
       Shipment_Line_API.Shipment_Connected_Lines_Exist(order_no, 'CUSTOMER_ORDER', line_no, rel_no, line_item_no) ShipmentExist,
       Cust_Order_Line_Address_API.Get_Country_Code(order_no, line_no, rel_no, line_item_no) DeliveryCountryCode,
       Exp_License_Connect_Head_API.Get_State_By_Ref(order_no, line_no, rel_no, line_item_no,Customer_Order_Line_API.Get_Expctr_License_Order_Type(demand_code_db, demand_order_ref1, demand_order_ref2, demand_order_ref3)) ExportLicenseStatusForFindAndConnect,
       (revised_qty_due - qty_shipped - open_shipment_qty + qty_shipdiff) ShipmentConnectableQty,
       PROJECT_API.Get_Program_Id(PROJECT_ID) ProgramId,
       PROJECT_API.Get_Name(PROJECT_ID) ProjectName,
       ACTIVITY_API.Get_Sub_Project_Id(ACTIVITY_SEQ) SubProjectId,
       ACTIVITY_API.Get_Activity_No(ACTIVITY_SEQ) ActivityNo,
       ACTIVITY_API.Get_Description(ACTIVITY_SEQ) ActivityDescription,
       Customer_Order_API.Get_Customer_No_Pay(ORDER_NO) CustomerNoPay,
       Customer_Order_API.Get_Customer_No_Pay_Addr_No(ORDER_NO) CustomerNoPayAddrNo,
       Condition_Code_API.Get_Description(condition_code) ConditionCodeDescription,
       Inventory_Part_API.Get_Unit_Meas(supply_site, part_no) InvPartSuppSiteUnitMeas,
       Inventory_Part_API.Get_Unit_Meas(contract, part_no) InvPartUnitMeas,
       Customer_Info_API.Get_Name(owning_customer_no) OwningCustomerName,
       DECODE(Sales_Part_API.Get_Taxable_Db(contract, catalog_no), 'TRUE', 'TRUE', 'FALSE') Taxable,
       DECODE(SIGN(buy_qty_due - qty_on_order - qty_assigned), '1', 'TRUE', 'FALSE') DeliveredLessThanPegged,
       Inventory_Part_API.Get_Planner_Buyer(contract, part_no) Planner,
       Customer_Order_API.Get_Authorize_Code(order_no) AuthorizeCode,
       Company_Localization_Info_API.Get_Enabled_Params_per_Company(company) EnabledLccParams,
       Customer_Order_Line_API.Get_Tax_Id_Type(order_no, line_no, rel_no, line_item_no) TaxIdType,
       Interim_Ctp_Critical_Path_API.Get_Ctp_Run_Id('CUSTOMERORDER', order_no, line_no, rel_no, line_item_no) CriticalPathId,
       Interim_Ctp_Manager_API.Get_Req_Date_Fulfilled(order_no, line_no, rel_no, line_item_no, ctp_planned_db, 'CUSTOMERORDER', planned_delivery_date) CapabilityCheckResult  
from CUSTOMER_ORDER_JOIN_CFV t
where to_date(substr(t.OBJVERSION, 0, 8), 'YYYYMMDD') between to_date('20181101', 'YYYYMMDD') AND  to_date('20240331', 'YYYYMMDD');
