SELECT t.* ,
       Site_API.Get_Company(Contract) Company,
       Company_Finance_API.Get_Currency_Code(company) Currency,
       Company_Tax_Control_API.Get_External_Tax_Cal_Method_Db(company) TaxCalcMethod,
       Customer_Info_Address_API.Get_Name(customer_no, ship_addr_no) DelAddrName,
       Customer_Info_Address_API.Get_Name(customer_no, bill_addr_no) BillAddrName,
       Customer_Tax_Free_Tax_Code_API.Get_Tax_Free_Tax_Code(customer_no, ship_addr_no, company, supply_country_db, '*') TaxFreeTaxCode,
       Site_Discom_Info_API.Get_Allow_Overrule_Limit_Sa_Db(contract) OverruleLimitSaleToAssort,
       Customer_Info_API.Get_Name(rebate_customer) RebateCustomerName,
       Customer_Info_API.Get_Name(customer_no) CustomerName,
       Customer_Info_API.Get_Name(customer_no_pay) CustomerNoPayName,
       Contact_Util_API.Get_Cust_Contact_Name(customer_no, bill_addr_no, cust_ref) CustRefName,
       Contact_Util_API.Get_Cust_Contact_Name(customer_no_pay, customer_no_pay_addr_no, customer_no_pay_ref) CustomerNoPayReferenceName,
       Sales_Part_Salesman_API.Get_Name(salesman_code) SalesPartSalesmanName,
       Payment_Term_API.Get_Description(company, pay_term_id) PaymentTermDescription,
       Shipment_Line_API.Shipment_Connected_Lines_Exist(order_no, 'CUSTOMER_ORDER') ShipmentConnectedLinesExist,
       Customer_Agreement_API.Get_Description(agreement_id) AgreementDescription,
       Supplier_Info_API.Get_Name(vendor_no) VendorName,
       Person_Info_API.Get_Name(main_representative_id) RepresentativeName,
       Customer_Info_Address_API.Get_Customer_Branch(customer_no, bill_addr_no) CustomerBranch,
       Freight_Zone_API.Get_Description(freight_map_id, zone_id) FreightZoneDescription,
       Forwarder_Info_API.Get_Name(forward_agent_id) ForwardName,
       Statutory_Fee_API.Get_Description(company, Customer_Tax_Free_Tax_Code_API.Get_Tax_Free_Tax_Code(customer_no, ship_addr_no, company, supply_country_db, '*')) TaxFreeTaxCodeDescription,
       Customer_Order_API.Get_Tax_Id_Type(order_no) TaxIdType,
       Customer_Addr_Tax_Number_API.Get_Tax_Id_Number(customer_no, ship_addr_no, company, 'IN', 'IN', 'GST') CustomerDeliveryTaxIdNumber,
       Customer_Addr_Tax_Number_API.Get_Tax_Id_Number(customer_no, bill_addr_no, company, 'IN', 'IN', 'GST') CustomerInvoiceTaxIdNumber 
from customer_order t
where to_date(substr(t.OBJVERSION, 0, 8), 'YYYYMMDD') between to_date('20181101', 'YYYYMMDD') AND  to_date('20240331', 'YYYYMMDD');
