SELECT t.*,
       DECODE(AUTHORIZED, 1, 'TRUE', 'FALSE') authorized,
       Company_Emp_API.Get_Name(company, empno) employee_name,
       Inventory_Part_API.Get_Description(contract, part_no) part_description,
       RESOURCE_SHARE * SETUP_TIME setup_resource_hours,
       RESOURCE_SHARE * MANUFACTURING_TIME resource_hours,
       Inventory_Transaction_Hist_API.Get_Cost(inv_transaction_id) *
       Inventory_Transaction_Hist_API.Get_Quantity(inv_transaction_id) inventory_cost_amount,
       Inventory_Transaction_Hist_API.Get_Reject_Code(inv_transaction_id) scrapping_cause,
       Scrapping_Cause_API.Get_Reject_Message(Inventory_Transaction_Hist_API.Get_Reject_Code(inv_transaction_id)) scrapping_cause_desc,
       CREW_SIZE * LABOR_SETUP_TIME setup_man_hours,
       CREW_SIZE * LABOR_TIME man_hours,
       Mpccom_Accounting_API.Error_Posting_Exists_String(ACCOUNTING_ID) has_erroneous_postings,
       Mpccom_Accounting_API.Transferred_Posting_Exists_Str(ACCOUNTING_ID) has_transferred_postings,
       Mpccom_Accounting_API.Get_Sum_Value(ACCOUNTING_ID, 'M40') w_i_p_build_up,
       Person_Info_API.Get_Name(user_id) user_name,
       Company_Emp_API.Get_Name(company, created_by_employee_id) created_by_employee_name,
       Transport_Delivery_Note_API.Get_Delivery_Reason_Id(transport_del_note_no) delivery_reason_id,
       Delivery_Reason_API.Get_Description(company,
                                           Transport_Delivery_Note_API.Get_Delivery_Reason_Id(transport_del_note_no)) delivery_reason_desc,
       Transport_Delivery_Note_API.Get_Alt_Delivery_Note_Id(transport_del_note_no) alt_delivery_note_no,
       Transport_Delivery_Note_API.Get_Create_Date(transport_del_note_no) delivery_note_date,
       DECODE(order_type_db,
              'PROD SCH',
              Production_Receipt_API.Get_Production_Line(ORDER_NO),
              NULL) production_line,
       DECODE(order_type_db,
              'PROD SCH',
              Production_Line_Rep_Point_API.Get_Description(contract,
                                                            Production_Receipt_API.Get_Production_Line(ORDER_NO),
                                                            report_point_id),
              NULL) report_point_desc
  FROM OPERATION_HISTORY t
 WHERE to_date(substr(t.OBJVERSION, 0, 8), 'YYYYMMDD') between
       to_date('20181101', 'YYYYMMDD') AND to_date('20240331', 'YYYYMMDD');
