SELECT t.*,
       Sales_Part_API.Get_Catalog_Desc(contract, catalog_no) part_description_in_use,
       DECODE(Part_Catalog_API.Get_Configurable_Db(NVL(part_no, catalog_no)),
              'CONFIGURED',
              'TRUE',
              'FALSE') configurable,
       DECODE(NVL(Inventory_Part_Supply_Type_API.Encode(Inventory_Part_Planning_API.Get_Order_Requisition(contract,
                                                                                                          part_no)),
                  '*'),
              'D',
              'TRUE',
              'FALSE') d_o_p,
       Part_Gtin_API.Get_Default_Gtin_No(catalog_no) g_t_i_n,
       Part_Weight_Volume_Util_API.Get_Partca_Net_Weight(contract,
                                                         catalog_no,
                                                         part_no,
                                                         sales_unit_meas,
                                                         conv_factor,
                                                         inverted_conv_factor,
                                                         Company_Invent_Info_API.Get_Uom_For_Weight(Company)) net_weight,
       Part_Weight_Volume_Util_API.Get_Partca_Net_Volume(contract,
                                                         catalog_no,
                                                         part_no,
                                                         sales_unit_meas,
                                                         conv_factor,
                                                         inverted_conv_factor,
                                                         Company_Invent_Info_API.Get_Uom_For_Volume(Company)) volume,
       DECODE(cust_warranty_id, null, 'FALSE', 'TRUE') customer_warranty,
       Sales_Part_API.Get_Catalog_Desc(contract, replacement_part_no) replacement_part_description,
       DECODE(Document_Text_API.Note_Id_Exist(note_id),
              '1',
              'TRUE',
              'FALSE') document_text       
  FROM  SALES_PART t
 WHERE to_date(substr(OBJVERSION, 0, 8), 'YYYYMMDD') between
       to_date('20181101', 'YYYYMMDD') AND to_date('20240331', 'YYYYMMDD');
